.TH "VIRGL_TEST_SERVER" 1 "29 September 2019" "Virgl-team" "User Commands"
.SH NAME
virgl_test_server \- rendering server for separating OpenGL clients from host hardware
.SH "SYNOPSIS"
.B virgl_test_server
[options] 
.SH DESCRIPTION
virgl_test_server provides a rendering server that interfaces with the OpenGL hardware.
Clients connect to it by using the mesa 3D virgl gallium software renderer. 

With the server running, the clients can connect to it by running it with specific environment
varibles set to make mesa pick the virgl driver for rendering: 

  LIBGL_ALWAYS_SOFTWARE=1 GALLIUM_DRIVER=virpipe <client software> 


.SH OPTIONS
.TP
--no-fork Run the server single threaded 
.TP
--no-loop-or-fork Run the server single threaded and exit after the client closes the connection
.TP
--use-gles Force a GLES context on the host 
.TP
--use-glx Use the GLX interface on the host
.TP
--use-egl-surfaceless Use the EGL surfaceless interface on the host
.SH "AUTHORS AND CONTRIBUTORS"
   Dave Airlie, Gert Wollny, Erik Faye-Lund, Marc-André Lureau, Gurchetan Singh,
   Emil Velikov, Robert Foss, Jakob Bornecrantz, Elie Tournier, Alexandros Frantzis,
   David Riley, Tomeu Vizoso, Li Qiang, Stéphane Marchesin, Chia-I Wu, Po-Hsien Wang,
   Lepton Wu, Ramin Azarmehr, Robert Tarasov, Michal Privoznik, Alexander Kanavin,
   Joe M. Kniss, Karol Herbst, Ondřej Súkup, Gerd Hoffmann, Ilia Mirkin, Joe Kniss,
   Nathan Gauer, Zhenyu Wang

